#header
name: SHAW
description: Keep it short. Keep it simple.
favicon: /fav.png
ga: ''

# Directory
root: /dairy/

#nav
nav:
    HOME: /
    ARCHIVE: /archives/

#post
excerpt_link: Continue Reading


#about me
aboutMeImg: /aboutme.jpg

github: https://github.com/yiliashaw
twitter: https://twitter.com/YiliaShaw
weibo: http://weibo.com/kathleenxiao

#copyright
themeLink: https://github.com/yiliashaw/hexo-theme-prince
